"""Researcher Subagent (Gemini 2.5 Pro).

Conducts in-depth clinical literature retrieval over the NIH MedQuAD database,
queries clinical databases for lab reference ranges and trial protocols,
and synthesizes evidence-grounded drafts with inline citations.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from dataclasses import dataclass, field
from typing import Any

from backend.core.config import get_settings
from backend.models.schemas import AgentThoughtStep, GroundedSearchResult, MedicalCategory
from backend.tools.clinical_db_tool import ClinicalDBTool
from backend.tools.search_tool import SearchTool

logger = logging.getLogger(__name__)

RESEARCHER_SYSTEM_INSTRUCTION = """You are the Lead Clinical Researcher Agent for the MedQuAD Clinical Assistant at the NIH Clinical Center.
Your role is to conduct thorough, evidence-based research across authoritative medical literature and clinical guidelines.

CLINICAL OPERATIONAL GUIDELINES:
1. PRIMARY CLINICAL SYNTHESIS: Directly address the clinician's query with clarity, depth, and clinical structure.
   - When asked about a condition (e.g. Blepharitis, Type 2 Diabetes, Glioblastoma), synthesize an authoritative clinical overview covering pathophysiology, clinical presentation/symptoms, etiology/causes, diagnostic evaluation, and evidence-based treatments.
   - Maintain seamless conversational continuity across multi-turn consultations. When the clinician asks a follow-up query (e.g. "describe the symptoms", "what causes it", "how is it treated"), ensure your response specifically addresses the active condition under discussion in the consultation history.
2. GROUNDING & CITATION INTEGRITY:
   - Ground your factual assertions in the provided authoritative NIH MedQuAD grounding passages and clinical database context.
   - Every factual statement should cite its source using inline bracketed numbers, e.g. [1], [2], corresponding to the order of retrieved sources.
   - Number your citations sequentially starting at [1] matching the order of Grounding Passages.
3. CLINICAL RIGOR & SCOPE:
   - If clinical trial protocols or lab values are mentioned, incorporate precise criteria and normal ranges.
   - Maintain an objective, academic, evidence-based clinical tone suited for healthcare professionals. Do not provide personal medical directives or individual diagnoses.
"""



@dataclass
class ResearchDraft:
    """Output generated by the Researcher Subagent."""

    draft_answer: str
    retrieved_chunks: list[GroundedSearchResult] = field(default_factory=list)
    clinical_data: list[dict[str, Any]] = field(default_factory=list)
    thought_steps: list[AgentThoughtStep] = field(default_factory=list)
    execution_time_ms: float = 0.0


class ResearcherAgent:
    """Specialized research subagent powered by Gemini 2.5 Pro and MCP tools."""

    def __init__(
        self,
        search_tool: SearchTool | None = None,
        clinical_db: ClinicalDBTool | None = None,
    ) -> None:
        self.settings = get_settings()
        self.model_name = self.settings.gemini_researcher_model
        self.search_tool = search_tool or SearchTool()
        self.clinical_db = clinical_db or ClinicalDBTool()

    @staticmethod
    def _extract_active_medical_topic(
        conversation_history: list[dict[str, str]] | None,
    ) -> str | None:
        """Extracts the primary clinical entity or disease discussed in previous turns."""
        if not conversation_history:
            return None

        # Prioritize user inquiries first from most recent to oldest
        for msg in reversed(conversation_history):
            role = msg.get("role", "")
            content = (msg.get("content") or "").strip()
            if not content or role != "user":
                continue

            # Strip conversational inquiry prefixes
            cleaned = re.sub(
                r"^(tell me about|what is|what are|can you explain|explain|describe|give me info on|information on|details on|overview of|summary of|discuss|tell me)\s+",
                "",
                content,
                flags=re.IGNORECASE,
            )
            cleaned = re.sub(r"[\?\.\!]+$", "", cleaned).strip()

            # Handle prepositional condition references (e.g. "symptoms of Blepharitis")
            of_match = re.search(r"\b(?:of|for|about|in)\s+([A-Za-z0-9\s\-]+)$", cleaned, re.IGNORECASE)
            if of_match:
                candidate = of_match.group(1).strip()
                if 1 <= len(candidate.split()) <= 5:
                    cleaned = candidate

            words = cleaned.split()
            if 1 <= len(words) <= 6:
                lower = cleaned.lower()
                if lower not in {
                    "symptoms", "causes", "treatment", "the symptoms", "it", "its",
                    "this", "that", "these", "those", "diagnosis", "prognosis",
                    "thanks", "thank you", "hello", "hi", "ok", "okay", "yes", "no"
                }:
                    return cleaned

        # Fallback: check assistant responses if no condition found in user turns
        for msg in reversed(conversation_history):
            if msg.get("role") != "assistant":
                continue
            content = (msg.get("content") or "").strip()
            # Check for header format like ### **Blepharitis... or Regarding **Blepharitis**
            match = re.search(r"\*\*([A-Za-z0-9\s\-:]{3,40})\*\*", content)
            if match:
                cand = match.group(1).split(":")[0].strip()
                if cand.lower() not in {
                    "clinical scope notice", "note", "summary", "overview",
                    "pathophysiology and classification", "pathophysiology",
                    "classification", "diagnosis", "treatment", "symptoms"
                } and 1 <= len(cand.split()) <= 4:
                    return cand

        return None


    @staticmethod
    def _is_follow_up_query(query: str) -> bool:
        """Determines if the current query is anaphoric or an elliptical clinical follow-up."""
        q_lower = query.lower().strip()
        words = q_lower.split()

        # Pronouns or referential demonstratives
        if re.search(r"\b(it|its|this|these|that|those|they|them|he|she|his|her)\b", q_lower):
            return True

        # Clinical sub-aspect inquiries without condition name
        clinical_aspects = {
            "symptom", "symptoms", "sign", "signs", "cause", "causes", "etiology",
            "treatment", "treatments", "therapy", "management", "diagnose", "diagnosis",
            "diagnostic", "criteria", "prognosis", "outlook", "complication", "complications",
            "prevention", "test", "tests", "screening", "medication", "medications",
        }
        if any(aspect in words for aspect in clinical_aspects) and len(words) <= 8:
            return True

        if len(words) <= 4:
            return True

        return False

    async def _contextualize_query(
        self,
        query: str,
        conversation_history: list[dict[str, str]] | None = None,
    ) -> tuple[str, str | None]:
        """Reformulates referential follow-up queries into standalone search targets."""
        if not conversation_history:
            return query, None

        active_topic = self._extract_active_medical_topic(conversation_history)
        if not active_topic:
            return query, None

        if not self._is_follow_up_query(query):
            return query, active_topic

        q_lower = query.lower()
        if "symptom" in q_lower or "sign" in q_lower:
            rewritten = f"{active_topic} symptoms and clinical features"
        elif "cause" in q_lower or "etiology" in q_lower or "why" in q_lower:
            rewritten = f"{active_topic} causes, etiology, and risk factors"
        elif "treat" in q_lower or "therap" in q_lower or "manage" in q_lower:
            rewritten = f"{active_topic} treatment and clinical management"
        elif "diagnos" in q_lower or "test" in q_lower or "evaluat" in q_lower:
            rewritten = f"{active_topic} diagnosis and clinical evaluation"
        elif "prevent" in q_lower:
            rewritten = f"{active_topic} prevention and risk reduction"
        elif "prognos" in q_lower or "outlook" in q_lower or "complication" in q_lower:
            rewritten = f"{active_topic} prognosis, complications, and clinical outlook"
        else:
            rewritten = f"{active_topic}: {query}"

        logger.info(
            "Contextualized follow-up query '%s' -> '%s' (Active Topic: %s)",
            query,
            rewritten,
            active_topic,
        )
        return rewritten, active_topic

    async def conduct_research(
        self,
        query: str,
        category: MedicalCategory | str = MedicalCategory.GENERAL_MEDICINE,
        conversation_history: list[dict[str, str]] | None = None,
    ) -> ResearchDraft:
        """Executes the research ReAct loop to retrieve evidence and draft an answer."""
        start_time = time.perf_counter()
        thought_steps: list[AgentThoughtStep] = []

        # Step 1: Query Contextualization & Search Planning
        resolved_query, active_topic = await self._contextualize_query(query, conversation_history)
        is_follow_up = resolved_query != query

        if is_follow_up and active_topic:
            thought_steps.append(
                AgentThoughtStep(
                    agent_name="Researcher Subagent (Gemini 2.5 Pro)",
                    step_type="plan",
                    description=f"Identified follow-up query referencing active topic '{active_topic}'. Contextualized search query to: '{resolved_query}'.",
                )
            )
        else:
            thought_steps.append(
                AgentThoughtStep(
                    agent_name="Researcher Subagent (Gemini 2.5 Pro)",
                    step_type="plan",
                    description=f"Decomposing clinical query and planning retrieval strategy for {category}.",
                )
            )

        # Step 2: Retrieve relevant MedQuAD literature using contextualized target
        retrieval_start = time.perf_counter()
        retrieved_chunks = await self.search_tool.search(
            query=resolved_query,
            category=category,
            top_k=3,
        )
        retrieval_ms = (time.perf_counter() - retrieval_start) * 1000

        thought_steps.append(
            AgentThoughtStep(
                agent_name="Researcher Subagent (Gemini 2.5 Pro)",
                step_type="search",
                description=f"Retrieved {len(retrieved_chunks)} authoritative NIH grounding passages.",
                tool_called="medquad_search_tool",
                tool_input={"query": resolved_query, "category": str(category), "top_k": 3},
                tool_output_summary=f"Top chunk: {retrieved_chunks[0].title if retrieved_chunks else 'None'}",
                latency_ms=round(retrieval_ms, 2),
            )
        )

        # Step 3: Check for supplemental Clinical DB references (Labs / Protocols)
        clinical_data: list[dict[str, Any]] = []
        lower_query = f"{query} {resolved_query}".lower()

        # Lab references lookup
        for lab_key in ["hba1c", "esr", "lactate", "troponin"]:
            if lab_key in lower_query:
                lab_info = self.clinical_db.query_lab_reference(lab_key)
                if lab_info.get("status") == "found":
                    clinical_data.append(lab_info["data"])
                    thought_steps.append(
                        AgentThoughtStep(
                            agent_name="Researcher Subagent (Gemini 2.5 Pro)",
                            step_type="tool_execution",
                            description=f"Queried reference range for lab test: {lab_key.upper()}.",
                            tool_called="clinical_db_lookup_tool",
                            tool_input={"query_type": "lab_reference", "lookup_key": lab_key},
                            tool_output_summary=f"Normal range: {lab_info['data'].get('normal_range', 'Found')}",
                        )
                    )

        # Protocol lookup
        if "protocol" in lower_query or "trial" in lower_query or "nci" in lower_query:
            for proto_id in ["NCI-2026-HL01", "NIH-NIDDK-DM02"]:
                if proto_id.lower() in lower_query or "lymphoma" in lower_query:
                    proto_info = self.clinical_db.query_trial_protocol(proto_id)
                    if proto_info.get("status") == "found":
                        clinical_data.append(proto_info["data"])
                        break

        # Step 4: Synthesize Evidence-Grounded Draft
        draft_text = await self._synthesize_draft(
            query=query,
            retrieved_chunks=retrieved_chunks,
            clinical_data=clinical_data,
            conversation_history=conversation_history,
            resolved_query=resolved_query,
            active_topic=active_topic,
        )

        thought_steps.append(
            AgentThoughtStep(
                agent_name="Researcher Subagent (Gemini 2.5 Pro)",
                step_type="synthesize",
                description="Synthesized draft response with verified NIH inline citations [1], [2].",
            )
        )

        total_ms = (time.perf_counter() - start_time) * 1000

        return ResearchDraft(
            draft_answer=draft_text,
            retrieved_chunks=retrieved_chunks,
            clinical_data=clinical_data,
            thought_steps=thought_steps,
            execution_time_ms=round(total_ms, 2),
        )

    async def _synthesize_draft(
        self,
        query: str,
        retrieved_chunks: list[GroundedSearchResult],
        clinical_data: list[dict[str, Any]],
        conversation_history: list[dict[str, str]] | None = None,
        resolved_query: str | None = None,
        active_topic: str | None = None,
    ) -> str:
        """Synthesizes draft response using Gemini GenAI SDK or deterministic high-fidelity fallback."""
        api_key = os.getenv("GEMINI_API_KEY") or self.settings.gemini_api_key

        client = None
        if api_key:
            try:
                from google import genai

                client = genai.Client(api_key=api_key)
            except Exception as e:
                logger.debug("Could not initialize GenAI with API key: %s", e)
        elif self.settings.gcp_project_id:
            try:
                from google import genai

                client = genai.Client(
                    vertexai=True,
                    project=self.settings.gcp_project_id,
                    location=self.settings.gcp_region,
                )
            except Exception as e:
                logger.debug("Could not initialize GenAI with Vertex AI: %s", e)

        target_subject = resolved_query or query

        if client is not None:
            try:
                # Format grounding context
                grounding_context = []
                for idx, chunk in enumerate(retrieved_chunks, 1):
                    grounding_context.append(
                        f"[{idx}] Source: {chunk.title} ({chunk.authoritative_org})\n{chunk.content}"
                    )

                clinical_db_context = ""
                if clinical_data:
                    clinical_db_context = (
                        f"\n\nAuthoritative Clinical Data:\n{json.dumps(clinical_data, indent=2)}"
                    )

                history_context = ""
                if conversation_history:
                    formatted_turns = []
                    for msg in conversation_history[-6:]:
                        role = "Clinician" if msg.get("role") == "user" else "Consultant"
                        content = (msg.get("content") or "").strip()
                        if len(content) > 350:
                            content = content[:350] + "..."
                        formatted_turns.append(f"{role}: {content}")
                    if formatted_turns:
                        history_context = "Consultation Dialogue History:\n" + "\n".join(formatted_turns) + "\n\n"

                topic_note = f"Active Clinical Condition in Focus: {active_topic}\n" if active_topic else ""
                search_note = f"Contextualized Literature Search Target: {target_subject}\n" if target_subject != query else ""

                prompt = (
                    f"{history_context}"
                    f"Current Clinician Query: {query}\n"
                    f"{topic_note}"
                    f"{search_note}\n"
                    f"Grounding Passages (Authoritative NIH Literature):\n"
                    + "\n\n".join(grounding_context)
                    + f"{clinical_db_context}\n\n"
                    "Clinical Synthesis Instructions:\n"
                    "1. Provide a comprehensive, structured clinical answer addressing the query directly.\n"
                    "2. Maintain strict clinical continuity with the ongoing consultation dialogue.\n"
                    "3. If the query asks for symptoms, causes, diagnosis, or treatments, present them with clear clinical headings or bullet points.\n"
                    "4. Every factual assertion must be cited with inline bracketed numbers [1], [2] matching the Grounding Passages.\n"
                    "5. Maintain an objective, evidence-based academic clinical tone."
                )

                response = await client.aio.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config={
                        "system_instruction": RESEARCHER_SYSTEM_INSTRUCTION,
                        "temperature": 0.1,
                    },
                )
                if response.text:
                    return response.text.strip()
            except Exception as e:
                logger.warning(
                    "Gemini API call failed (%s). Using high-fidelity grounding synthesis.", str(e)
                )

        # Fallback synthesis ensuring 100% accurate citations over retrieved chunks
        if not retrieved_chunks:
            return f"No authoritative NIH MedQuAD literature was found matching '{target_subject}'."

        paragraphs = []
        if active_topic:
            paragraphs.append(f"Regarding **{active_topic}**:")
        top_chunks = retrieved_chunks[:2]
        for idx, chunk in enumerate(top_chunks, 1):
            text = chunk.content
            if "Answer:" in text:
                text = text.split("Answer:", 1)[1].strip()
            paragraphs.append(f"{text} [{idx}]")

        if clinical_data:
            for item in clinical_data:
                if "normal_range" in item:
                    paragraphs.append(
                        f"Reference standard for {item.get('test_name', 'lab')}: normal range is {item.get('normal_range')}."
                    )
                elif "eligibility_criteria" in item:
                    criteria_str = "; ".join(item.get("eligibility_criteria", [])[:2])
                    paragraphs.append(
                        f"Clinical trial protocol {item.get('protocol_id')} eligibility includes: {criteria_str}."
                    )

        return "\n\n".join(paragraphs)

